### ISSUE TITLE
Excuse me, what is this question

### ISSUE THREAD

**Issue by yueliang-x** [ranjan-mohanty/vfs-appointment-bot#71]
[2024-07-02 18:19:39,263] Frame.goto() missing 1 required positional argument: 'url'
Traceback (most recent call last):
  File "F:\vfs-appointment-bot-main\vfs-appointment-bot-main\vfs_appointment_bot\main.py", line 89, in main
    appointment_found = vfs_bot.run(args)
  File "F:\vfs-appointment-bot-main\vfs-appointment-bot-main\vfs_appointment_bot\vfs_bot\vfs_bot.py", line 80, in run
    page.goto(vfs_url)
  File "F:\vfs-appointment-bot-main\vfs-appointment-bot-main\env\lib\site-packages\playwright\sync_api\_generated.py", line 8686, in goto
    self._sync(
  File "F:\vfs-appointment-bot-main\vfs-appointment-bot-main\env\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "F:\vfs-appointment-bot-main\vfs-appointment-bot-main\env\lib\site-packages\playwright\_impl\_page.py", line 519, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
TypeError: Frame.goto() missing 1 required positional argument: 'url'

**Comment by piyushhanchate** [comment]
I'm facing the same issue

**Comment by rollercoaster** [comment]
This seems to get fixed if we add the following to config, depending on your country code:

```
[vfs-url]
IN-IT = https://visa.vfsglobal.com/ind/en/ita/login
```

But it still doesnt work as it fails on the "Reject cookies" step. Is this repo being updated?
