### ISSUE TITLE
Playwright timeout errors 

### ISSUE THREAD

**Issue by joshi1207** [ranjan-mohanty/vfs-appointment-bot#82]
**Describe the bug**
playwright._impl._errors.timeouterror: locator.click: timeout 30000ms exceeded 

**To Reproduce**

Run the script as usual, fill in the parameters

**Expected behavior**
It should open VFS url.

**Screenshots**

<img width="541" alt="image" src="https://github.com/user-attachments/assets/85de28c2-2034-4c71-a43d-ca3528929861">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser [e.g. chrome, safari] firefox

**Smartphone (please complete the following information):**

**Additional context**

Activate Windows
Go to Settings to activate Windows.

PS C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\vfs_appointment_bot> vfs-appointment-bot -sc IN -dc DE
[REDACTED] Starting VFS Bot for IN-DE
Enter the visa center: Bangalore - Visa Application Centre
Enter the visa category: National Visa (stay of more than 90 days): Student Visa
Enter the visa sub category: D Student visa: students with APS certificate
[REDACTED] Locator. click: Timeout 30000ms exceeded.
Call log:
Naiting for get_by_role("button", name="Reject All")
Traceback (most recent call last):
File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\vfs_appointment_bot\main.py", line 89, in main
appointment_found = vfs_bot.run(args)

File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\vfs_appointment_bot\vfs_bot\vfs_bot.py", line 81, in run
self.pre_login_steps(page)
File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\vfs_appointment_bot\vfs_bot\vfs_bot_de.py", line 80, in pre_log
in_steps
policies_reject_button.click()
File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 15093, in click
self ._ sync(
File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
return task.result()
AAAAAAAAAAAAA
File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_locator.py", line 156, in click
return await self ._ frame. click(self ._ selector, strict=True, ** params)

File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 488, in click
await self ._ channel.send("click", locals_to_params(locals()))
File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
return await self ._ connection.wrap_api_call(
AAAAAAAAAAAAAAAAAAAAAA
File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
raise rewrite_error(error, f"{parsed_st['apiName' ]}: {error}") from None
playwright ._ impl ._ errors. TimeoutError: Locator. click: Timeout 30000ms exceeded.
Call log:
Naiting for get_by_role("button", name="Reject All")

PS C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\vfs_appointment_bot>

**Comment by amm47** [comment]
Same

**Comment by okflow** [comment]
if any body can expert in making bot i have some project for that devloper

whatsapp- +60 13-908 8506

**Comment by maravilhosinga** [comment]
Same here.

**Comment by jmk47912204** [comment]
Same here

**Comment by ghoshsuman** [comment]
Facing the same error. Any solutions? Does this bot still work @ranjan-mohanty ?
